{% set name = "gwtc-tools" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gwtc_tools-{{ version }}.tar.gz
  sha256: 6672e0a735f816ca7ee230ea92e641e02e5f614f062e6532eccb03f5137e3b42

build:
  entry_points:
    - gwtc_update_pipeline_gevents = gwtc:gwtc_update_pipeline_gevents
    - gwtc_diff = gwtc:gwtc_diff
    - gwtc_get_gevent_coinc_files = gwtc:gwtc_get_gevent_coinc_files
    - gwtc_create_from_query = gwtc:gwtc_create_from_query
    - gwtc_test = gwtc:gwtc_test
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=3.4.3
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - ligo-gracedb
    - pyyaml
    - cbcflow

test:
  imports:
    - gwtc
  commands:
    - pip check
    - gwtc_update_pipeline_gevents --help
    - gwtc_diff --help
    - gwtc_get_gevent_coinc_files --help
    - gwtc_create_from_query --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.ligo.org/chad-hanna/gwtc
  summary: A package for gwtc operations, including interactions with gracedb
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - chadhanna
